[package]
name = "wrath-worldserver"
version = "0.1.0"
authors = ["victov <victor.veldstra@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version="*", features=["attributes"] }
async-trait = {version="0.1"}
anyhow = { version = "1.0" }
podio = { version = "0.2" } 
dotenvy = { version="*" }
rand = { version = "0.8" } 
num-traits = { version = "0.2" } 
num_enum = { version="0.5" } 
wrath-auth-db = { path="../databases/wrath-auth-db" }
wrath-realm-db = { path="../databases/wrath-realm-db" }
chrono = { version = "0.4" }
bit_field = { version = "0.10" }
async-ctrlc = {version="1.2", features=["termination"] }
time = { version = "0.3", features = ["macros"] }
tracing = {version="0.1"}
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
rstar = { version = "0.9" }
hex = { version = "0.4" }
cmdparse = { version = "0.1" }

wow_srp = { version = "0.6.0" }
wow_dbc = { version = "0.2", features = ["wrath"] }
wow_world_base = { git="https://github.com/gtker/wow_messages.git", rev="55c2b641b7dbd09ca1de882f5fce814e4a91c068", features=["extended"] }
wow_world_messages = { git="https://github.com/gtker/wow_messages.git", rev="55c2b641b7dbd09ca1de882f5fce814e4a91c068", features=["wrath", "async-std", "chrono"] }
wow_items = { git="https://github.com/gtker/wow_messages.git", rev="55c2b641b7dbd09ca1de882f5fce814e4a91c068", features = ["wrath"] }
wow_spells = { version = "0.1.0", features = ["vanilla", "tbc", "wrath"] }


#For local testing purposes, one may want to switch to this local path version of wow_world_messages. Do not commit with this though
#wow_world_messages = { path = "../../wow_messages/wow_world_messages", features=["wrath", "async-std", "chrono"] }

